## Analysis of times

In [15]:
import re 
import ast
import pandas as pd

from pathlib import Path

from pre_processing_utils import Utils

In [16]:
# folder_path = Path(r"/Users/edgarjoseandradelotero/Library/CloudStorage/GoogleDrive-andradeed78@gmail.com/My Drive/UCDavis/Nested games/data/new")
folder_path = Path.cwd().parent / "data" / "new"

dict_worker_id = {}
for subdir in folder_path.iterdir():
    if subdir.is_dir():
        df = pd.read_csv(subdir / "Request.csv")
        worker_id_list = []
        for key, row in df.iterrows():
            value = row['unique_id']
            if isinstance(value, str):
                value_ = value.split(':')[0]
                if value_ not in worker_id_list:
                    worker_id_list.append(value_)
        dict_worker_id[subdir.name] = {
            idx  + 1: value for idx, value in enumerate(worker_id_list)
        }
dict_worker_id

{'05-25-batch-1': {1: '61798ab0f4a0bbfe7c050433',
  2: '699d0fdf43b9ecfcafe7e52a',
  3: '62cbf51439a76e8fccd8a495',
  4: '6a036a8dcb5fdb1ea688ba0a',
  5: '670dc79e7b17f1b1ac7bdf95',
  6: '671bbaf1bec15d847b871b9b',
  7: '69808f7c8ff246c7ce92f77c',
  8: '69ee2e8675301578c95e1e60',
  9: '5e8a1827052175000938eb91',
  10: '68d4401a239d0533f8a66382',
  11: '6a0df5493e7bdfb3e8ad4caa',
  12: '67adcef788620db2ba190704',
  13: '6651e26558b5973c2cff426b',
  14: '66cff35bdee873a6ca915b84',
  15: '66723b1f7c3cf6961f0868a3',
  16: '6a048950bab3f5d03e6ef938',
  17: '6a013494bc1e80e3a152897c',
  18: '672c57a8ee24c76a011bf4d7',
  19: '66324d7b75233b6df004695d',
  20: '695c47f824a839c308d41292',
  21: '69ff52565942ff463af813fa',
  22: '69ef194605c1cba63afeba0b',
  23: '5563984afdf99b672b5749b6',
  24: '68238de3a3ba8b99fef9b7ca',
  25: '60e282f9202a8126e2ea0315',
  26: '67b631294f6039a20633b917',
  27: '65b571deec1559505fc20ac3',
  28: '606e3cce02e2e8a8c965ca75',
  29: '67f2e613c09bbf379bd208ea',
  30: '6993957ffe43ec54a046b703',
  31: '63ffcb367b500c516d0648a2'}}

In [17]:
# folder_path = Path(r"/Users/edgarjoseandradelotero/Library/CloudStorage/GoogleDrive-andradeed78@gmail.com/My Drive/UCDavis/Nested games/data/new")
folder_path = Path.cwd().parent / "data" / "new"

df_list = []
for subdir in folder_path.iterdir():
    if subdir.is_dir():
        df = pd.read_csv(subdir / "Response.csv")
        df['batch'] = subdir.name
        df_list.append(df)

df = pd.concat(df_list, ignore_index=True)
print(df.shape)
df.head(2)

(2161, 16)

,vars,id,creation_time,failed,failed_reason,time_of_death,type,participant_id,question,answer,page_type,successful_validation,metadata_,class,object_type,batch
0,{},1,2026-05-26 00:13:08,False,NaN,NaN,Response,1,consent_choice,I consent,ConsentPageWrapper,True,"{""time_taken"": 1.883, ""platform"": ""Chrome 147....",Response,_Response,05-25-batch-1
1,{},2,2026-05-26 00:13:21,False,NaN,NaN,Response,1,tutorial,NaN,ModularPage,True,"{""time_taken"": 11.604, ""platform"": ""Chrome 147...",Response,_Response,05-25-batch-1

In [18]:
df["time_taken"] = df['metadata_'].apply(
    lambda x: Utils.str_to_dict(x)["time_taken"]
)
df.head(2)

,vars,id,creation_time,failed,failed_reason,time_of_death,type,participant_id,question,answer,page_type,successful_validation,metadata_,class,object_type,batch,time_taken
0,{},1,2026-05-26 00:13:08,False,NaN,NaN,Response,1,consent_choice,I consent,ConsentPageWrapper,True,"{""time_taken"": 1.883, ""platform"": ""Chrome 147....",Response,_Response,05-25-batch-1,1.883
1,{},2,2026-05-26 00:13:21,False,NaN,NaN,Response,1,tutorial,NaN,ModularPage,True,"{""time_taken"": 11.604, ""platform"": ""Chrome 147...",Response,_Response,05-25-batch-1,11.604

In [19]:
# df_times = df.groupby(['batch', 'participant_id', 'page_type'])['time_taken'].describe().reset_index()
df_times = df.groupby(['batch', 'page_type'])['time_taken'].describe()
df_times

                                     count       mean         std    min  \
batch         page_type
05-25-batch-1 ConsentPageWrapper      29.0  77.533897  120.034218  1.883
              GuessingCoinsGamePage   68.0   8.459029    5.861966  1.191
              InfoPage                59.0  18.898949   29.044747  0.753
              InnerAcceptancePage     39.0   4.810359    3.786941  1.301
              InnerProposalPage       39.0   9.259538    5.211074  2.300
              InnerWaitingPage        99.0   1.847091    0.209170  0.549
              ModularPage            114.0  25.811167   48.199026  0.108
              OuterAcceptancePage     44.0   4.560750    3.639970  0.802
              OuterProposalPage       44.0   7.012886    4.038693  2.012
              OuterWaitingPage       402.0   1.878848    0.170064  0.453
              ScorePage               82.0   2.695378    1.308525  0.810
              TimedModularPage       262.0   5.573363    3.069695  0.846
              WaitPage               880.0   1.000333    0.766798  0.014

                                         25%      50%        75%      max
batch         page_type
05-25-batch-1 ConsentPageWrapper     8.50700  21.5400  108.26600  511.979
              GuessingCoinsGamePage  3.34800   6.7775   13.44300   19.844
              InfoPage               4.37500  11.4190   22.65800  198.579
              InnerAcceptancePage    2.69100   3.8070    5.08950   19.801
              InnerProposalPage      5.98300   8.4700    9.86050   26.356
              InnerWaitingPage       1.69650   1.9050    1.96700    2.514
              ModularPage            1.30625   2.0525   11.88750  239.709
              OuterAcceptancePage    2.18475   3.2265    5.60425   15.775
              OuterProposalPage      4.63025   5.6590    7.86675   21.853
              OuterWaitingPage       1.79350   1.9150    1.97300    3.004
              ScorePage              1.72375   2.3780    3.22700    7.280
              TimedModularPage       3.59325   4.8785    6.54175   22.220
              WaitPage               0.35775   0.4970    1.97800    2.016

In [20]:
round_time = 0
for key, time_taken in df.groupby(['batch', 'page_type'])['time_taken']:
    batch, page_type = key
    if page_type in [
            'ConsentPageWrapper', 'GuessingCoinsGamePage',
            'TimedModularPage ', 'InnerWaitingPage '
            'OuterProposalPage	', 'OuterAcceptancePage', 'OuterWaitingPage '
            'InnerProposalPage ', 'InnerAcceptancePage ', 'ScorePage '
        ]:
        round_time += time_taken.mean()
print(f"Average time taken per round = {Utils.format_time(round_time)}")
print(f"Estimated total time based on average = {Utils.format_time(round_time * 25)}")

Average time taken per round = 1:30
Estimated total time based on average = 37:43

In [21]:
df.groupby(['batch'])['time_taken'].describe()

,count,mean,std,min,25%,50%,75%,max
batch,,,,,,,,
05-25-batch-1,2161.0,5.293322,21.054643,0.014,0.984,1.968,3.171,511.979

In [22]:
total_time = df.groupby(['batch', 'participant_id'])['time_taken'].sum().mean()
print(f"Average total time = {Utils.format_time(total_time)}")

Average total time = 6:34

In [23]:
HOURLY_PAYMENT = 25
SECONDS_PAYMENT = HOURLY_PAYMENT / (60 * 60)

for key, grp in df.groupby(['batch', 'participant_id']):
    batch, participant_id = key
    total_time = grp['time_taken'].sum()
    print(f'Id: {participant_id} --- Worker {dict_worker_id[batch][participant_id]} => {Utils.format_time(total_time)} time taken -> payment: {round(SECONDS_PAYMENT * total_time, 2)}')

Id: 1 --- Worker 61798ab0f4a0bbfe7c050433 => 1:32 time taken -> payment: 0.64
Id: 2 --- Worker 699d0fdf43b9ecfcafe7e52a => 6:43 time taken -> payment: 2.81
Id: 3 --- Worker 62cbf51439a76e8fccd8a495 => 0:26 time taken -> payment: 0.18
Id: 4 --- Worker 6a036a8dcb5fdb1ea688ba0a => 6:32 time taken -> payment: 2.72
Id: 5 --- Worker 670dc79e7b17f1b1ac7bdf95 => 7:22 time taken -> payment: 3.07
Id: 6 --- Worker 671bbaf1bec15d847b871b9b => 9:12 time taken -> payment: 3.84
Id: 7 --- Worker 69808f7c8ff246c7ce92f77c => 9:46 time taken -> payment: 4.07
Id: 8 --- Worker 69ee2e8675301578c95e1e60 => 2:9 time taken -> payment: 0.9
Id: 9 --- Worker 5e8a1827052175000938eb91 => 3:1 time taken -> payment: 1.26
Id: 10 --- Worker 68d4401a239d0533f8a66382 => 2:4 time taken -> payment: 0.86
Id: 11 --- Worker 6a0df5493e7bdfb3e8ad4caa => 11:9 time taken -> payment: 4.65
Id: 12 --- Worker 67adcef788620db2ba190704 => 4:20 time taken -> payment: 1.81
Id: 13 --- Worker 6651e26558b5973c2cff426b => 4:52 time taken -> payment: 2.03
Id: 14 --- Worker 66cff35bdee873a6ca915b84 => 2:57 time taken -> payment: 1.23
Id: 16 --- Worker 6a048950bab3f5d03e6ef938 => 9:42 time taken -> payment: 4.04
Id: 17 --- Worker 6a013494bc1e80e3a152897c => 6:33 time taken -> payment: 2.73
Id: 18 --- Worker 672c57a8ee24c76a011bf4d7 => 8:0 time taken -> payment: 3.34
Id: 19 --- Worker 66324d7b75233b6df004695d => 3:46 time taken -> payment: 1.57
Id: 21 --- Worker 69ff52565942ff463af813fa => 5:42 time taken -> payment: 2.38
Id: 22 --- Worker 69ef194605c1cba63afeba0b => 6:41 time taken -> payment: 2.79
Id: 23 --- Worker 5563984afdf99b672b5749b6 => 7:54 time taken -> payment: 3.3
Id: 24 --- Worker 68238de3a3ba8b99fef9b7ca => 0:51 time taken -> payment: 0.35
Id: 25 --- Worker 60e282f9202a8126e2ea0315 => 14:34 time taken -> payment: 6.07
Id: 26 --- Worker 67b631294f6039a20633b917 => 21:3 time taken -> payment: 8.78
Id: 27 --- Worker 65b571deec1559505fc20ac3 => 5:51 time taken -> payment: 2.44
Id: 28 --- Worker 606e3cce02e2e8a8c965ca75 => 12:38 time taken -> payment: 5.27
Id: 29 --- Worker 67f2e613c09bbf379bd208ea => 7:1 time taken -> payment: 2.93
Id: 30 --- Worker 6993957ffe43ec54a046b703 => 4:39 time taken -> payment: 1.94
Id: 31 --- Worker 63ffcb367b500c516d0648a2 => 3:23 time taken -> payment: 1.42

In [24]:
filter_out = ['69e98427d1347065e42d8dc3',
 '695bd68349914a703c6a9e80',
 '69ffdfd55e31e4326c1e64bf',
 '69d672f63c0229f70584d183',
 '666b0b42bb6fa2822fa27a32',
 '69aeec32d642e2a0092f6452',
 '6723422d5f63c70998014b03',
 ]
filter_out = [str(x) for x in filter_out]

counter = 0
for key, grp in df.groupby(['batch', 'participant_id']):
    counter += 1
    batch, participant_id = key
    total_time = grp['time_taken'].sum()
    worker_id = dict_worker_id[batch][participant_id]
    if str(worker_id) not in filter_out:
        print(f'{worker_id}, {round(SECONDS_PAYMENT * total_time, 2)}')

print(f"Shown {counter} participants")

61798ab0f4a0bbfe7c050433, 0.64
699d0fdf43b9ecfcafe7e52a, 2.81
62cbf51439a76e8fccd8a495, 0.18
6a036a8dcb5fdb1ea688ba0a, 2.72
670dc79e7b17f1b1ac7bdf95, 3.07
671bbaf1bec15d847b871b9b, 3.84
69808f7c8ff246c7ce92f77c, 4.07
69ee2e8675301578c95e1e60, 0.9
5e8a1827052175000938eb91, 1.26
68d4401a239d0533f8a66382, 0.86
6a0df5493e7bdfb3e8ad4caa, 4.65
67adcef788620db2ba190704, 1.81
6651e26558b5973c2cff426b, 2.03
66cff35bdee873a6ca915b84, 1.23
6a048950bab3f5d03e6ef938, 4.04
6a013494bc1e80e3a152897c, 2.73
672c57a8ee24c76a011bf4d7, 3.34
66324d7b75233b6df004695d, 1.57
69ff52565942ff463af813fa, 2.38
69ef194605c1cba63afeba0b, 2.79
5563984afdf99b672b5749b6, 3.3
68238de3a3ba8b99fef9b7ca, 0.35
60e282f9202a8126e2ea0315, 6.07
67b631294f6039a20633b917, 8.78
65b571deec1559505fc20ac3, 2.44
606e3cce02e2e8a8c965ca75, 5.27
67f2e613c09bbf379bd208ea, 2.93
6993957ffe43ec54a046b703, 1.94
63ffcb367b500c516d0648a2, 1.42
Shown 29 participants

In [28]:
filter_in = [
'6a036a8dcb5fdb1ea688ba0a', '699d0fdf43b9ecfcafe7e52a',
       '5e8a1827052175000938eb91', '671bbaf1bec15d847b871b9b',
       '69808f7c8ff246c7ce92f77c',
       '6a048950bab3f5d03e6ef938', '672c57a8ee24c76a011bf4d7',
       '6a0df5493e7bdfb3e8ad4caa', '65b571deec1559505fc20ac3',
       '6993957ffe43ec54a046b703', '67f2e613c09bbf379bd208ea',
       '63ffcb367b500c516d0648a2'
 ]
filter_in = [str(x) for x in filter_in]

counter = 0
for key, grp in df.groupby(['batch', 'participant_id']):
    batch, participant_id = key
    total_time = grp['time_taken'].sum()
    worker_id = dict_worker_id[batch][participant_id]
    if str(worker_id) in filter_in:
        counter += 1
        print(f'{worker_id}, {round(SECONDS_PAYMENT * total_time, 2)}')

print(f"Shown {counter} participants")

699d0fdf43b9ecfcafe7e52a, 2.81
6a036a8dcb5fdb1ea688ba0a, 2.72
671bbaf1bec15d847b871b9b, 3.84
69808f7c8ff246c7ce92f77c, 4.07
5e8a1827052175000938eb91, 1.26
6a0df5493e7bdfb3e8ad4caa, 4.65
6a048950bab3f5d03e6ef938, 4.04
672c57a8ee24c76a011bf4d7, 3.34
65b571deec1559505fc20ac3, 2.44
67f2e613c09bbf379bd208ea, 2.93
6993957ffe43ec54a046b703, 1.94
63ffcb367b500c516d0648a2, 1.42
Shown 12 participants